//  Foursquare API keys:
export const CLIENT_ID = 'RKCGALVVUJB3VUVFF1SVFEMJPATOGTUXBKUG20CU0BWLLLK2';
export const CLIENT_SECRET = 'KGJOZLQU4NGJN1ZZE1L5212VRFUTVG5L4L0GS35XDHHE0DE5';

//   Google Maps API key
export const MAP_KEY = 'AIzaSyBlWBQXfU8gPU4XOoEWFe7lbU5fjxqsQXc';
